theme: jekyll-theme-minimal

# Site settings
title: Jekyll Doc Theme
email: your-email@domain.com
description: >
  Jekyll Template for Project Websites
  providing documentation and blog post pages.
lang: en-US
