# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"

# gem 'jekyll-admin', group: :jekyll_plugins

# gem "rails"


group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
end