# docker build -f .devcontainer/Dockerfile_Ruby -t who0joe/jekyll .devcontainer

FROM ruby:3.1.2-bullseye

ENV TZ=Asia/Seoul 

# Install bundler, latest jekyll
RUN gem install bundler jekyll


# Git Config
RUN apt-get update \
    && apt-get -y install --no-install-recommends git

RUN git config --system core.ignorecase false; \
 	git config --system core.autocrlf true; \
    git config --system pull.rebase false