# docker build -f .devcontainer/Dockerfile_Ruby -t who0joe/jekyll .devcontainer

FROM ruby:3.1.2-bullseye

# ENV Variables required by Jekyll
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    TZ=Asia/Seoul \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US

# Install bundler, latest jekyll
RUN gem install bundler jekyll

RUN apt-get update \
    && apt-get -y install --no-install-recommends git

RUN git config --system core.ignorecase false; \
 	git config --system core.autocrlf true